language: go
git:
  quiet: true

before_install:
- go get -t -v ./...

script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
- go build

after_success:
- bash <(curl -s https://codecov.io/bash)
- ./tag-nightly.sh

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "bin/*"
  skip_cleanup: true
  on:
    tags: true
